---
title: "Exploratory data analysis"
author: "Oluwayomi Akinfenwa"
date: "27/11/2023"
output:
  html_document:
    toc: yes
    toc_depth: '4'
    df_print: paged
  bookdown::html_document2:
    toc: no
    toc_float: yes
    toc_depth: 4
    number_sections: yes
  pdf_document:
    toc: yes
    toc_depth: '4'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(knitr.duplicate.label = 'allow')
```

### Loading necessary packages

```{r, libraries, include = FALSE}
library(lme4)
library(tidybayes)
library(ggplot2)
library(dplyr)
library(tidyr)
library(rjags)
library(R2jags)
library(bayesplot)
library(patchwork)
library(ggragged)
```

Loading the R.data containing the learning-tower data set and the processed data with Region and Income classification.

```{r loading the data}
load(here::here("SavedData", "pisam.Rdata"))
```

### Filtering European countries alone

```{r Europe}
Pisa_Europe_Data <- Pisa_Data |> filter(Continent == "Europe") |> arrange(Country)
```

**For the European countries, we have 230 observations from 40 countries.**

### Visualising the data

```{r Europe}
# Joining the Income and Region together to form one new column
Pisa_Europe_Data <- unite(Pisa_Europe_Data, col = "Income_Region", c("Income", "Region"), sep = "_", remove = FALSE)

#Creating the grid for the prediction
country_names <- levels(factor(Pisa_Europe_Data$Country))
region_names <- levels(factor(Pisa_Europe_Data$Region))
income_names <- levels(factor(Pisa_Europe_Data$Income))
incomeregion_names <- levels(factor(Pisa_Europe_Data$Income_Region))

## Obtaining the index for the data
mu_index <- 1:nrow(Pisa_Europe_Data)

## Obtaining the region indexes

country_region <- Pisa_Europe_Data |> group_by(Country) |>
  summarise(Region=first(Region)) |>
  mutate(Country_num = as.numeric(as.factor(Country))) |>
  mutate(region_num = as.numeric(as.factor(Region)))

REGION <- country_region |> select(Country, Region)

## Obtaining the income indexes

country_income <- Pisa_Europe_Data |> group_by(Country) |>
  summarise(Income=first(Income)) |>
  mutate(Country_num = as.numeric(as.factor(Country))) |>
  mutate(income_num = as.numeric(as.factor(Income)))
         
INCOME <- country_income |> select(Country, Income)

## Obtaining the income_region indexes

country_incomeregion <- Pisa_Europe_Data |> group_by(Country) |>
  summarise(Income_Region=first(Income_Region)) |>
  mutate(Country_num = as.numeric(as.factor(Country))) |>
  mutate(incomeregion_num = as.numeric(as.factor(Income_Region)))

Country_region <- country_region |> left_join(INCOME, join_by(Country))
Country_income <- country_income |> left_join(REGION, join_by(Country))
```

### Fitting lm model on PISA maths data

```{r}
library(broom)
## The function reframe- creates a new data-frame by applying functions t columns of an existing data frame.

Model_est <-Pisa_Europe_Data |>
  nest_by(Country) |>
  mutate(mod = list(lm(math ~ year_orig, data = data))) |>
  reframe(tidy(mod))|>
   select(Country, term, estimate)

Model_est <- Model_est |>
  pivot_wider(names_from = term, values_from = estimate) 
Model_Est <- Model_est |>
  rename("slope" = "year_orig") |>
  mutate(slopesign = sign(slope)) |>
  left_join(Country_region, join_by(Country)) |>
  select(-c(Country_num, region_num)) |>
  arrange(slope)
  
##Merging the slope-sign with the Pisa data so that I can rearrange by both country and slope-sign

Slopesign <-  Model_Est |>
  select(Country, slope)

Pisa_Europe_Data1 <- Pisa_Europe_Data |>
  left_join(Slopesign, join_by(Country))

Pisa_Europe_Data1$facet <- factor(Pisa_Europe_Data1$Region, 
                  levels = c("Western Europe", "Eastern Europe", "Northern Europe", "Southern Europe"))

Model_Est$facet <- factor(Model_Est$Region, 
                  levels = c("Western Europe", "Eastern Europe", "Northern Europe", "Southern Europe"))

```


### The plot

#### Grouped by region

```{r}

pdf("Model_fit(grouped by Region).pdf",
    width = 12,
    height = 8)
ggplot(data = Pisa_Europe_Data1,
         aes(x=year_orig, y=math))+
  geom_point(color = "grey25")+
   geom_abline(data=Model_Est, 
               aes(slope=slope, intercept= `(Intercept)`,color = factor(slopesign)))+
  facet_ragged_rows(vars(facet), vars(reorder(Country, slope)),scales = "free_y",
                    switch = "y", labeller=label_wrap_gen(width=6))+
  scale_x_continuous(labels = function(x) x+2000, breaks = seq(0,18,3))+
  scale_y_continuous(position = "right")+
   labs(x= " ", y = " ",  color = "Slope") + scale_color_manual(values = c("maroon", "blue3"), labels = c("negative", "positive"), na.translate = F)+
  theme(legend.position = "bottom",
        plot.subtitle = element_text(family = "Serif"),
        axis.text.x = element_text(angle = 45, hjust = 0.5, vjust = 0.5, face = "bold"),strip.text.x = element_text(size = 9,face = "bold"),
        axis.text.y = element_text(size = 9,face = "bold"))
dev.off()
```


#### Grouped by Income

```{r}
pdf("Model_fit(grouped by Income).pdf",
    width = 12,
    height = 8)

middle_income <- ggplot(data = filter(Pisa_Europe_Data1, Income== "Middle Income"),
         aes(x=year_orig, y=math))+
  geom_point(color = "grey25")+
   geom_abline(data= filter(Model_Est, Income== "Middle Income"), 
               aes(slope=slope, intercept= `(Intercept)`,color = factor(slopesign)))+
  ggh4x::facet_wrap2(vars(Income, reorder(Country, slope)), ncol = 10,
  strip = ggh4x::strip_nested(bleed = TRUE))+
  labs(x = " ", y = " ", color = "Slope") +
  scale_color_manual(values = c("blue3","maroon"), labels = c("positive","negative"), na.translate = F)+
  scale_y_continuous(position = "right",breaks = seq(350,490, 40))+
  scale_x_continuous(labels = function(x) x+2000, breaks = seq(0,18,3))+
  theme(legend.position = "none", strip.text.x = element_text(size = 8.5,face = "bold"),
        axis.text.x = element_text(angle = 45, hjust = 0.5, vjust = 0.5))

high_income <- ggplot(data = filter(Pisa_Europe_Data1, Income== "High Income"),
         aes(x=year_orig, y=math))+
  geom_point(color = "grey25")+
   geom_abline(data= filter(Model_Est, Income== "High Income"), 
               aes(slope=slope, intercept= `(Intercept)`,color = factor(slopesign)))+
  ggh4x::facet_wrap2(vars(Income, reorder(Country, slope)), ncol = 10,
  strip = ggh4x::strip_nested(bleed = TRUE))+
  labs(x = " ", y = " ", color = "Slope") +
  scale_color_manual(values = c("maroon", "blue3"), labels = c("negative", "positive"), na.translate = F)+
  scale_y_continuous(position = "right")+
  scale_x_continuous(labels = function(x) x+2000, breaks = seq(0,18,3))+
  theme(legend.position = "none", strip.text.x = element_text(size = 8.5,face = "bold"),
        axis.text.x = element_text(angle = 45, hjust = 0.5, vjust = 0.5))

high_income/middle_income +
  plot_layout(widths = 1, heights = c(3, 1))

dev.off()
```


